### PR TITLE
Add config_settings for platforms

### PR DESCRIPTION
**Pull request by keith**
This is a common pattern you need to select on. Since we have a limited
set of CPUs it's nice to provide a source of truth for this type of
thing

### CODE REVIEW

**Comment by keith** [comment]
looking for feedback, not sure if we should do this or not, but i figured i'd submit for discussion (right now it's missing many cpus)

**Comment by jszumski** [comment]
I've replicated something similar into a couple different projects already, so a single canonical list seems like a great idea 👍

**Comment by keith** [comment]
Can you share what you have for this so we make sure we cover it?

**Comment by jszumski** [comment]
```
[
    config_setting(
        name = type,
        values = {"apple_platform_type": type},
    )
    for type in [
        "ios",
        "macos",
        "tvos",
        "watchos",
    ]
]

[
    config_setting(
        name = cpu,
        values = {"cpu": cpu},
    )
    for cpu in [
        "darwin_x86_64",
        "darwin_arm64",
        "darwin_arm64e",
        "ios_i386",
        "ios_x86_64",
        "ios_armv7",
        "ios_armv7s",
        "ios_arm64",
        "ios_arm64e",
        "ios_sim_arm64",
        "tvos_x86_64",
        "tvos_arm64",
        "tvos_sim_arm64",
        "watchos_arm64_32",
        "watchos_armv7k",
        "watchos_i386",
        "watchos_x86_64",
    ]
]

selects.config_setting_group(
    name = "any_device",
    match_any = [
        ":ios_armv7",
        ":ios_armv7s",
        ":ios_arm64",
        ":ios_arm64e",
        ":tvos_arm64",
        ":watchos_arm64_32",
        ":watchos_armv7k",
    ],
)

selects.config_setting_group(
    name = "any_simulator",
    match_any = [
        ":ios_i386",
        ":ios_x86_64",
        ":ios_sim_arm64",
        ":tvos_x86_64",
        ":tvos_sim_arm64",
        ":watchos_i386",
        ":watchos_x86_64",
        ":watchos_arm64",
    ],
)
```

**Comment by cgrindel** [comment]
I am about to add this one to `swift_bazel`.

```python
[
    config_setting(
        name = type,
        values = {"apple_platform_type": type},
    )
    for type in [
        "ios",
        "macos",
        "tvos",
        "watchos",
    ]
]
```

**Comment by keith** [comment]
ok i added those constraints here except for the apple_platform_type one. i don't feel strongly but i feel like we should leave that out since ideally things moves towards platforms instead and we don't rely on that as much going forward. but happy to add if folks think we should

**Pull request merged**
